version: '3'
services:
  proxy:
    build: ./
    container_name: reserve-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./templates/:/etc/nginx/templates/:rw,cached
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
